# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdee2dce3c82a43fda20ea1243bf9157d40341095579599288dea324b0708d14133e6a2fc1c4f762fedc8f0f8bdbc12a0ea5b95cb25ab81d01ffd91644ea4a62

test:
  secret_key_base: fb33a0c97dde6fcc79cbe1c9d6f45768f27a041c3bb91bc5c766ccfa7333caacdf835cc3e08e9bd0bd9c457d37984fe7168d510a0462135d7a9ca9c9d40ac17e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
